### ISSUE TITLE
`maintenance-custom-page-cmd` command not found

### ISSUE THREAD

**Issue by thepuzzlemaster** [dokku/dokku-maintenance#15]
## Description of problem
More details [here](https://github.com/dokku/dokku/discussions/5302). 
When running the `maintenance:custom-page` command, I receive the following error:
```
dokku maintenance:custom-page my-app < /tmp/maintenance.tar
/var/lib/dokku/plugins/enabled/maintenance/subcommands/custom-page: line 6: maintenance-custom-page-cmd: command not found
```

I believe I have tracked down the issue to the [most recent PR](https://github.com/dokku/dokku-maintenance/pull/14/files#diff-ada0ba3b1255490d74197cffb40c6b87f4406742f1fad0f322a23c8cab953e23L7), which renamed this specific command, but perhaps didn't include the rename in this subcommands file.

When I used nano to update the name referenced in subcommands/custom-page, line 6 to point to `cmd-maintenance-custom-page`, the command ran fine.

But looking through the tests, it would seem like the tests for this should have failed? Are the tests running? 

### How reproducible
In my case, I added the maintenance plugin to my dokku instance, and then attempted to add a custom-page tarball.

### Steps to Reproduce

1. setup dokku app
2. install plugin
3. scp .tar file to dokku server
4. `dokku maintenance:custom-page my-app < path/to/maintenance.tar

#### Actual Results
Received error: `/var/lib/dokku/plugins/enabled/maintenance/subcommands/custom-page: line 6: maintenance-custom-page-cmd: command not found`

#### Expected Results
Command runs correctly

## Environment Information

root@staging:/var/lib/dokku# dokku report my-app
-----> uname: Linux staging.my-app.pro 4.15.0-134-generic #138-Ubuntu SMP Fri Jan 15 10:52:18 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
-----> memory:
                     total        used        free      shared  buff/cache   available
       Mem:           3944         426         818           2        2699        3235
       Swap:             0           0           0
-----> docker version:
       Client: Docker Engine - Community
        Version:           20.10.11
        API version:       1.41
        Go version:        go1.16.9
        Git commit:        dea9396
        Built:             Thu Nov 18 00:37:08 2021
        OS/Arch:           linux/amd64
        Context:           default
        Experimental:      true

       Server: Docker Engine - Community
        Engine:
         Version:          20.10.11
         API version:      1.41 (minimum version 1.12)
         Go version:       go1.16.9
         Git commit:       847da18
         Built:            Thu Nov 18 00:35:16 2021
         OS/Arch:          linux/amd64
         Experimental:     false
        containerd:
         Version:          1.4.12
         GitCommit:        7b11cfaabd73bb80907dd23182b9347b4245eb5d
        runc:
         Version:          1.0.2
         GitCommit:        v1.0.2-0-g52b36a2
        docker-init:
         Version:          0.19.0
         GitCommit:        de40ad0
-----> docker daemon info:
       Client:
WARNING: No swap limit support
        Context:    default
        Debug Mode: true
        Plugins:
         app: Docker App (Docker Inc., v0.9.1-beta3)
         buildx: Build with BuildKit (Docker Inc., v0.6.3-docker)
         scan: Docker Scan (Docker Inc., v0.9.0)

       Server:
        Containers: 1
         Running: 1
         Paused: 0
         Stopped: 0
        Images: 19
        Server Version: 20.10.11
        Storage Driver: overlay2
         Backing Filesystem: extfs
         Supports d_type: true
         Native Overlay Diff: true
         userxattr: false
        Logging Driver: json-file
        Cgroup Driver: cgroupfs
        Cgroup Version: 1
        Plugins:
         Volume: local
         Network: bridge host ipvlan macvlan null overlay
         Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
        Swarm: inactive
        Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
        Default Runtime: runc
        Init Binary: docker-init
        containerd version: 7b11cfaabd73bb80907dd23182b9347b4245eb5d
        runc version: v1.0.2-0-g52b36a2
        init version: de40ad0
        Security Options:
         apparmor
         seccomp
          Profile: default
        Kernel Version: 4.15.0-134-generic
        Operating System: Ubuntu 18.04.6 LTS
        OSType: linux
        Architecture: x86_64
        CPUs: 2
        Total Memory: 3.852GiB
        Name: staging.my-app.pro
        ID: FK62:4UZE:FTZE:2QJI:I7NC:WQBE:GNOR:M66Y:CWLQ:55AK:6R75:UI5S
        Docker Root Dir: /var/lib/docker
        Debug Mode: false
        Registry: https://index.docker.io/v1/
        Labels:
        Experimental: false
        Insecure Registries:
         127.0.0.0/8
        Live Restore Enabled: false

-----> git version: git version 2.17.1
-----> sigil version: 0.7.1build+1ec3006
-----> herokuish version:
       herokuish: 0.5.33
       buildpacks:
         heroku-buildpack-multi     v1.0.0
         heroku-buildpack-ruby      v232
         heroku-buildpack-nodejs    v189
         heroku-buildpack-clojure   v87
         heroku-buildpack-python    v204
         heroku-buildpack-java      v69
         heroku-buildpack-gradle    v35
         heroku-buildpack-scala     v91
         heroku-buildpack-play      v26
         heroku-buildpack-php       v201
         heroku-buildpack-go        v157
         heroku-buildpack-nginx     v15
         buildpack-null             v3
-----> dokku version: dokku version 0.26.6
-----> plugn version: plugn: 0.7.1build+9bf216b
-----> dokku plugins:
         00_dokku-standard    0.26.6 enabled    dokku core standard plugin
         20_events            0.26.6 enabled    dokku core events logging plugin
         app-json             0.26.6 enabled    dokku core app-json plugin
         apps                 0.26.6 enabled    dokku core apps plugin
         apt                  0.12.0 enabled    Inject deb packages into dokku based on files in project
         builder              0.26.6 enabled    dokku core builder plugin
         builder-dockerfile   0.26.6 enabled    dokku core builder-dockerfile plugin
         builder-herokuish    0.26.6 enabled    dokku core builder-herokuish plugin
         builder-null         0.26.6 enabled    dokku core builder-null plugin
         builder-pack         0.26.6 enabled    dokku core builder-pack plugin
         buildpacks           0.26.6 enabled    dokku core buildpacks plugin
         certs                0.26.6 enabled    dokku core certificate management plugin
         checks               0.26.6 enabled    dokku core checks plugin
         common               0.26.6 enabled    dokku core common plugin
         config               0.26.6 enabled    dokku core config plugin
         cron                 0.26.6 enabled    dokku core cron plugin
         docker-options       0.26.6 enabled    dokku core docker-options plugin
         domains              0.26.6 enabled    dokku core domains plugin
         enter                0.26.6 enabled    dokku core enter plugin
         git                  0.26.6 enabled    dokku core git plugin
         http-auth            0.6.2 enabled    HTTP authentication for apps
         letsencrypt          0.12.1 enabled    Automated installation of let's encrypt TLS certificates
         logs                 0.26.6 enabled    dokku core logs plugin
         maintenance          0.7.1 enabled    Maintenance mode for apps
         network              0.26.6 enabled    dokku core network plugin
         nginx-vhosts         0.26.6 enabled    dokku core nginx-vhosts plugin
         plugin               0.26.6 enabled    dokku core plugin plugin
         proxy                0.26.6 enabled    dokku core proxy plugin
         ps                   0.26.6 enabled    dokku core ps plugin
         registry             0.26.6 enabled    dokku core registry plugin
         repo                 0.26.6 enabled    dokku core repo plugin
         resource             0.26.6 enabled    dokku core resource plugin
         run                  0.26.6 enabled    dokku core run plugin
         scheduler            0.25.6 enabled    dokku core scheduler plugin
         scheduler-docker-local 0.26.6 enabled    dokku core scheduler-docker-local plugin
         scheduler-null       0.26.6 enabled    dokku core scheduler-null plugin
         shell                0.26.6 enabled    dokku core shell plugin
         ssh-keys             0.26.6 enabled    dokku core ssh-keys plugin
         storage              0.26.6 enabled    dokku core storage plugin
         trace                0.26.6 enabled    dokku core trace plugin
=====> my-app app-json information
       App json computed selected:    app.json
       App json global selected:      app.json
       App json selected:
=====> my-app app information
       App created at:                1660289537
       App deploy source:             my-app
       App deploy source metadata:    my-app
       App dir:                       /home/dokku/my-app
       App locked:                    false
=====> my-app builder information
       Builder build dir:
       Builder computed build dir:
       Builder computed selected:
       Builder global build dir:
       Builder global selected:
       Builder selected:
=====> my-app builder-dockerfile information
       Builder dockerfile computed dockerfile path: Dockerfile
       Builder dockerfile global dockerfile path: Dockerfile
       Builder dockerfile dockerfile path:
=====> my-app builder-pack information
       Builder pack computed projecttoml path: project.toml
       Builder pack global projecttoml path: project.toml
       Builder pack projecttoml path:
=====> my-app buildpacks information
       Buildpacks computed stack:     gliderlabs/herokuish:latest-20
       Buildpacks global stack:
       Buildpacks list:
       Buildpacks stack:
=====> my-app ssl information
       Ssl dir:                       /home/dokku/my-app/tls
       Ssl enabled:                   true
       Ssl hostnames:                 staging.my-app.pro
       Ssl expires at:                Sep 22 05:22:47 2022 GMT
       Ssl issuer:                    C = US, O = Let's Encrypt, CN = R3
       Ssl starts at:                 Jun 24 05:22:48 2022 GMT
       Ssl subject:                   subject=CN = staging.my-app.pro
       Ssl verified:                  self signed
=====> my-app checks information
       Checks disabled list:          none
       Checks skipped list:           none
=====> my-app cron information
       Cron task count:               0
=====> my-app docker options information
       Docker options build:
       Docker options deploy:         --restart=on-failure:10
       Docker options run:
=====> my-app domains information
       Domains app enabled:           true
       Domains app vhosts:            staging.my-app.pro
       Domains global enabled:        true
       Domains global vhosts:         staging.my-app.pro
=====> my-app git information
       Git deploy branch:             master
       Git global deploy branch:      master
       Git keep git dir:              false
       Git rev env var:               GIT_REV
       Git sha:                       0b893317
       Git last updated at:           1660289537
=====> my-app http-auth information
       Http auth enabled:             true
=====> my-app logs information
       Logs computed max size:        10m
       Logs global max size:          10m
       Logs global vector sink:
       Logs max size:
       Logs vector sink:
=====> my-app maintenance information
       Maintenance enabled:           true
=====> my-app network information
       Network attach post create:
       Network attach post deploy:
       Network bind all interfaces:          false
       Network computed attach post create:
       Network computed attach post deploy:
       Network computed bind all interfaces: false
       Network computed initial network:
       Network computed tld:
       Network global attach post create:
       Network global attach post deploy:
       Network global bind all interfaces:   false
       Network global initial network:
       Network global tld:
       Network initial network:
       Network static web listener:
       Network tld:
       Network web listeners:                172.17.0.3:5000
=====> my-app nginx information
       Nginx access log format:
       Nginx access log path:         /var/log/nginx/my-app-access.log
       Nginx bind address ipv4:
       Nginx bind address ipv6:       ::
       Nginx client max body size:
       Nginx disable custom config:   false
       Nginx error log path:          /var/log/nginx/my-app-error.log
       Nginx global hsts:             true
       Nginx computed hsts:           true
       Nginx hsts:
       Nginx hsts include subdomains: true
       Nginx hsts max age:            15724800
       Nginx hsts preload:            false
       Nginx proxy buffer size:       4096
       Nginx proxy buffering:         on
       Nginx proxy buffers:           8 4096
       Nginx proxy busy buffers size: 8192
       Nginx proxy read timeout:      60s
       Nginx last visited at:         1660411420
       Nginx x forwarded for value:   $remote_addr
       Nginx x forwarded port value:  $server_port
       Nginx x forwarded proto value: $scheme
       Nginx x forwarded ssl:
=====> my-app proxy information
       Proxy enabled:                 true
       Proxy port map:                http:80:5000 https:443:5000
       Proxy type:                    nginx
=====> my-app ps information
       Deployed:                      true
       Processes:                     1
       Ps can scale:                  true
       Ps computed procfile path:     Procfile
       Ps global procfile path:       Procfile
       Ps procfile path:
       Ps restart policy:             on-failure:10
       Restore:                       true
       Running:                       true
       Status web 1:                  running (CID: 4a24ee3f0dd)
=====> my-app registry information
       Registry computed image repo:      dokku/my-app
       Registry computed push on release: false
       Registry computed server:
       Registry global push on release:
       Registry global server:
       Registry image repo:
       Registry push on release:
       Registry server:
       Registry tag version:
=====> my-app resource information
=====> my-app scheduler information
       Scheduler computed selected:   docker-local
       Scheduler global selected:     docker-local
       Scheduler selected:
=====> my-app scheduler-docker-local information
       Scheduler docker local disable chown:
       Scheduler docker local parallel schedule count:
=====> my-app storage information
       Storage build mounts:
       Storage deploy mounts:
       Storage run mounts:

### How (deb/make/rpm) and where (AWS, VirtualBox, physical, etc.) was Dokku installed?:
I'm not 100% sure on how Dokku was installed, as a different dev did the install. But I believe it was manually installed on a DigitalOcean ubuntu droplet.

### Additional information
I believe the issue has been identified above, but happy to run any of these additional commands if it would be helpful.

- App container inspect output (if applicable) via `dokku ps:inspect APP_NAME`
- The nginx configuration (if applicable) via `dokku nginx:show-config APP_NAME`
- Link to the exact repository being deployed (if possible/applicable):
- Output of failing Dokku commands after running `dokku trace:on`
  (BEWARE: `trace:on` will print environment variables for some commands, be sure you're not exposing any sensitive information when posting issues. You may replace these values with XXXXXX):

**Comment by thepuzzlemaster** [comment]
Also, I'm happy to create a PR to fix this, but given that I think the tests should be failing, I'd like for someone more familiar to confirm my findings before I do. As there's a good chance I'm also just doing something wrong here.

Thanks.

**Comment by josegonzalez** [comment]
Doesn't seem like we run tests since we dropped travis-ci.
