### ISSUE TITLE
Doesn't work with traefik

### ISSUE THREAD

**Issue by chapterjason** [dokku/dokku-maintenance#20]
## Description of problem

Doesn't work with traefik as proxy

### Steps to Reproduce

1. Enable traefik as proxy
2. Enable maintenance for app

#### Actual Results

Shows the application

#### Expected Results

Shows the maintenance page

**Comment by josegonzalez** [comment]
This plugin isn't meant to work with traefik. You'll probably need to look into direct integration with traefik for that. Here is a plugin that appears to do something like this: https://plugins.traefik.io/plugins/637ba08fc672f04dd500d1a1/maintenance-page

**Comment by chapterjason** [comment]
@josegonzalez I understand, I thought about finding a solution which would be working for all the other proxies too. Like running a dedicated static-server container which will respond with the maintenance page. Might be a bit of work.
