### ISSUE TITLE
Maintenance Except a Few IP Addresses?

### ISSUE THREAD

**Issue by aadrian** [dokku/dokku-maintenance#5]
Hi,

Would it be possible to have the "maintenance" mode work for everybody except a few IP addresses?

E.g. for an admin from one (of the few) IP addresses to be able to check the application after it's deployed and running, but still everybody else to see the maintenance.html ?

Thank you.

**Comment by josegonzalez** [comment]
Thats not possible with this plugin.

**Comment by rNoz** [comment]
Do you plan to support it?

At least can be "easy", like `maintentance on --allow 78.78.56.56` (single IP) to allow, and then `if ($remote_addr != 78.78.56.56) ...` show the maintenance page.

**Comment by josegonzalez** [comment]
I do not plan to support it.

If someone would like to add the functionality with tests, I would consider merging it.

If someone would like to sponsor the work, I've published a document on doing so [here](https://github.com/dokku/.github/blob/master/SPONSORING.md).

**Comment by josegonzalez** [comment]
I'm going to close this. The plugin does what it says on the tin, and anything more would be a bit difficult/out of scope.

If anyone would like to sponsor the work, feel free to checkout [this doc](https://github.com/dokku/.github/blob/master/SPONSORING.md). As always, pull requests welcome!
