### ISSUE TITLE
Custom page options

### ISSUE THREAD

**Issue by knzudgt** [dokku/dokku-maintenance#8]
I am interested in adding a custom page for maintenance to my Ruby on Rails application.
Is a tarball necessary for the custom page?
Even if in the examples it is not specified, I suppose a full path is necessary when we instruct dokku to import the custom page, such as:

    $ dokku maintenance:custom-page my-app < app/views/static-pages/my-custom-page.tar

So I wonder if I can indicate to dokku a `html` file in my application path, as follows:

    $ dokku maintenance:custom-page my-app < app/views/static-pages/maintenance.html

**Comment by josegonzalez** [comment]
Yeah for the moment, that is the case. There isn't really a great way to check the filetype of stdin without writing it to a file. We could pass it as the first argument though and then check based on the extension.

**Comment by josegonzalez** [comment]
I'm going to close this. The plugin does what it says on the tin, and anything more would be a bit difficult/out of scope.

If anyone would like to sponsor the work, feel free to checkout [this doc](https://github.com/dokku/.github/blob/master/SPONSORING.md). As always, pull requests welcome!
